environment: local

server:
  port: "3001"
  writetimeout: 15s
  readtimeout: 15s
  idletimeout: 60s
  ctx_timeout: 10s

log:
  environment: dev
  level: info
  format: json
db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: postgres
  maxopenconn: 50
  maxconnlifetime: 5s
  maxidle: 5s
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pooltimeout: 10s
  dialtimeout: 10s
  writetimeout: 5s
  readtimeout: 5s
